/**
 * Module 4 - Secure Hash & Encrypt Tool
 * 
 * This module demonstrates secure cryptographic operations using Node.js crypto:
 * - SHA-256 hashing for data integrity verification
 * - AES-256-GCM (Galois/Counter Mode) for authenticated encryption
 * - High-entropy key generation (256-bit)
 * 
 * The script prompts user for a message, then:
 * 1. Generates a cryptographic key and IV
 * 2. Creates a SHA-256 hash of the original message
 * 3. Encrypts the message using AES-256-GCM with authentication
 * 4. Decrypts and verifies data integrity by comparing hashes
 * 
 * @requires crypto - Node.js built-in cryptography module
 * @requires prompt-sync - Interactive command-line prompting
 */

import crypto from 'crypto';
import promptSync from 'prompt-sync';

/**
 * Prompt instance for synchronous user input
 * @type {Function}
 */
const prompt = promptSync({ sigint: true });

console.log('Module 4 - Secure Hash & Encrypt Tool (SHA-256 + AES-256-GCM)\n');

/**
 * Get user input message
 * The message will be encrypted, hashed, and then decrypted to verify integrity
 * @type {string}
 */
const message = prompt('Enter a message to secure: ').trim();

if (!message) {
  console.log('No message provided. Exiting.');
  process.exit(1);
}

/**
 * Generate a cryptographically secure 256-bit (32-byte) key
 * This key will be used for AES-256-GCM encryption
 * @type {Buffer}
 */
const key = crypto.randomBytes(32);

console.log('\n256-bit key generated (shown as hex for demonstration):');
console.log(key.toString('hex'));

/**
 * Compute SHA-256 hash of the original message
 * Used for integrity verification - to ensure data isn't tampered with
 * @type {string} Hexadecimal representation of the hash
 */
const originalHash = crypto
  .createHash('sha256')
  .update(message, 'utf8')
  .digest('hex');

console.log('\nOriginal Hash (SHA-256):', originalHash);

/**
 * Encrypt message using AES-256-GCM (Advanced Encryption Standard)
 * - 256-bit key size provides strong encryption
 * - GCM mode provides authenticated encryption (confidentiality + authenticity)
 * - IV (Initialization Vector) is 12 bytes, randomly generated for each encryption
 */

/**
 * Initialization Vector for AES-GCM
 * Unique for each encryption to prevent patterns in ciphertext
 * @type {Buffer} 12-byte random buffer
 */
const iv = crypto.randomBytes(12);

/**
 * Cipher object for AES-256-GCM encryption
 * @type {Cipher}
 */
const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);

/**
 * Encrypt the message
 * @type {string} Hexadecimal representation of encrypted data
 */
let encryptedData = cipher.update(message, 'utf8', 'hex');
encryptedData += cipher.final('hex');

/**
 * Authentication tag for verifying ciphertext integrity and authenticity
 * Generated by GCM mode to detect tampering
 * @type {Buffer} 16-byte authentication tag
 */
const authTag = cipher.getAuthTag();

/**
 * Encrypted package containing all necessary data for decryption
 * @type {Object}
 * @property {string} iv - Initialization vector (hex encoded)
 * @property {string} encryptedData - Encrypted message (hex encoded)
 * @property {string} authTag - GCM authentication tag (hex encoded)
 * @property {string} originalHash - SHA-256 hash for integrity verification
 */
const encryptedPackage = {
  iv: iv.toString('hex'),
  encryptedData,
  authTag: authTag.toString('hex'),
  originalHash
};

console.log('\nEncrypted Package:');
console.log(JSON.stringify(encryptedPackage, null, 2));

/**
 * DECRYPTION PROCESS
 * Reverse the encryption using the same key and IV
 * The authentication tag verifies that data hasn't been tampered with
 */

/**
 * Decipher object for AES-256-GCM decryption
 * Reconstructs the cipher using the same IV from the encrypted package
 */
const decipher = crypto.createDecipheriv(
  'aes-256-gcm',
  key,
  Buffer.from(encryptedPackage.iv, 'hex')
);

/**
 * Set the authentication tag for GCM mode verification
 * If ciphertext was modified, this will throw an error during decryption
 */
decipher.setAuthTag(Buffer.from(encryptedPackage.authTag, 'hex'));

/**
 * Decrypt the message
 * Will throw if authentication tag verification fails
 * @type {string} Decrypted message in UTF-8 format
 */
let decrypted = decipher.update(encryptedPackage.encryptedData, 'hex', 'utf8');
decrypted += decipher.final('utf8');

/**
 * Compute SHA-256 hash of decrypted message
 * If this matches originalHash, data integrity is verified
 * @type {string} Hexadecimal representation of hash
 */
const computedHash = crypto
  .createHash('sha256')
  .update(decrypted, 'utf8')
  .digest('hex');

/**
 * Verify data integrity by comparing original and computed hashes
 * Both must match if no tampering occurred
 * @type {boolean} True if hashes match, false if data was modified
 */
const integrityVerified = computedHash === encryptedPackage.originalHash;

console.log('\nDecrypted Message:');
console.log(decrypted);

console.log('\nIntegrity Verification:');
if (integrityVerified) {
  console.log('SUCCESS: Hash matches! Data integrity is preserved.');
} else {
  console.log('FAILED: Hash mismatch! Data has been tampered with.');
}

console.log('\nOriginal Hash  :', encryptedPackage.originalHash);
console.log('Computed Hash  :', computedHash);
